name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  modern:
    name: Node v12-16
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx uvu tests/ test.*
  legacy:
    name: Node v6-10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10
          - 8
          - 6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx uvu tests/ test.cjs
